name: CI-Polaris-TS-AN
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
     - name: checkout-bitbucket
       #run: git clone ${{ BITBUCKET_REPO_URL }}
       run: git clone https://waizguy@bitbucket.org/jwpolaris/auth0-iproov-demo.git
     - name: Setup Node.js environment
       uses: actions/setup-node@v4.0.3
       with:
    # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
         node-version:  10.15.1
    # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
    # node-version-file: # opti
    
    # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
         cache: npm
    # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
         cache-dependency-path: /home/runner/work/auth0-iproov-demo/*
     - run: sh pwd, ls -l  
     - name: Polaris Scan
       uses: synopsys-sig/synopsys-action@v1.11.0
       env: 
        DETECT_DETECTOR_SEARCH_DEPTH: 10
       with:
         ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_name: AJW-${{ github.event.repository.name }}
          


 
