name: CI-Polaris-TS-AN
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
     - name: checkout-bitbucket
       run: git clone ${{ BITBUCKET_REPO_URL }}
     - name: Polaris Scan
       uses: synopsys-sig/synopsys-action@v1.11.0
       with:
         ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_name: AJW-${{ github.event.repository.name }}
          


 
